"""empty message

Revision ID: a740233ae1ba
Revises: d39643c2fc8f
Create Date: 2022-05-10 16:52:50.775708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a740233ae1ba'
down_revision = 'd39643c2fc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    # ### end Alembic commands ###
