"""empty message

Revision ID: bbae9d21065c
Revises: 116859316d7f
Create Date: 2022-05-10 18:04:51.013606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbae9d21065c'
down_revision = '116859316d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_title', sa.String(length=15), nullable=False),
    sa.Column('report_desc', sa.String(length=1200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'report', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'report_id')
    op.drop_table('report')
    # ### end Alembic commands ###
